### ISSUE TITLE
Determinar como nos constituimos como Instrumento Legal (Etica)

### ISSUE THREAD

**Issue by CryptoEmpireR4** [16th-Tech-Group/ARGBroker-Demo#1]
Durante la primer reunión de Meet coordinamos en que tipo de organización nos íbamos a constituir de manera legal para llevar a cabo el trabajo.

**Comment by CryptoEmpireR4** [comment]
Durante el debate nos constituiremos como monotributista y trabajaremos como cuentapropistas independientes. El plazo del contrato, entre cuentapropistas, del 03 de abril del corriente año y se finalizara el 31 de diciembre del corriente año.

**Comment by GuillermoGiraudo7** [comment]
Dentro del contrato de trabajo firmado con la empresa contratante se especifica como una de sus cláusulas que la base de datos y el código programado serán de propiedad de la empresa, por lo cual no podremos exigir ninguna compensación por derechos de autor en un futuro.
Además otra de las cláusulas detalla que en el caso de que nos cambien como proveedores, se cobrará un 30% adicional del monto establecido en el contrato para el desarrollo de la aplicación en concepto de indemnización, así como también para la tarea de migración del servicio al nuevo proveedor se cobrarán las horas dedicadas a dicha actividad según los aranceles fijados por el Colegio de Informáticos de la Provincia de Córdoba.
