### ISSUE TITLE
Cuando los programadores de ARGBroker incurren en una negligencia, a que instrumento legal se acude y quien.

### ISSUE THREAD

**Issue by CryptoEmpireR4** [16th-Tech-Group/ARGBroker-Demo#11]
En proceso.

**Comment by ValeGuglielmetti** [comment]
Al momento que uno de los programadores de ARGBroker comete una negligencia, se debe acudir a la Ley 26.388 ( Ley sobre el Delito Informático), a Ley Nacional N° 11.723(Régimen Legal de la Propiedad Intelectual) y en como en este caso la situacion es planteada en la Provincia de Córdoba, tambien se acude al Consejo profesional de ciencias informáticas de Córdoba.
