### ISSUE TITLE
Cómo ARGBroker debe implementar seguridad según la Ley de Protección de Datos Personales.

### ISSUE THREAD

**Issue by CryptoEmpireR4** [16th-Tech-Group/ARGBroker-Demo#12]
En proceso.

**Comment by Fran7890** [comment]
Mediante los siguientes Artículos (9,15,30) de la Ley 25.326 la empresa ARGBroker les ofrece a sus clientes  mediante un contrato que a través de los artículo   mencionados se establecerá unos métodos de paso  de conducta , a través de la  ley ante mencionada y se le ofrecerá total confiabilidad  en sus datos personales y seguridad total.
El responsable o usuario del archivo de datos debe adoptar las medidas técnicas y organizativas que resulten necesarias para garantizar la seguridad y confidencialidad de los datos personales, de este modo evitaremos su adulteración , perdida o tratamiento no autorizado del cliente.La información debe ser suministrada en forma clara, exenta de codificaciones y en su caso acompañada de una explicación, en lenguaje accesible de la población, de los términos que se utilicen.
En ningún caso se podrá revelar los datos pertenecientes a terceros, aun cuando se vinculen o desvinculen con el interesado.
Los colaboradores de la organización respetaran unos  códigos de conducta  , que establezcan normas para el tratamiento de datos personales que tiendan a asegurar y mejorar las condiciones de operación de los sistemas de información.
