### ISSUE TITLE
Si el cliente decide reemplazar a ARGBroker por otro proveedor, describir cómo se debe actuar de manera ética ante el cliente y los colegas.

### ISSUE THREAD

**Issue by CryptoEmpireR4** [16th-Tech-Group/ARGBroker-Demo#13]
En proceso.

**Comment by Fran7890** [comment]
Mediante la Ley 25.326 se le informará  de manera ética al cliente de la empresa  ARGBroker  que mediante el Artículo 10  se respetara  la confidencialidad , el responsable y las personas que intervengan  en cualquier momento del proceso de los datos personales  y que están obligados por el secreto profesional  de guardar los datos y no compartirlos con nadie, tal obligación  subsistirá aun después de finalizada su relación con el titular del cliente.
