### ISSUE TITLE
Documentación del diseño del diagrama de clases

### ISSUE THREAD

**Issue by GuillermoGiraudo7** [16th-Tech-Group/ARGBroker-Demo#18]
TÍTULO: "Diagrama de Clases de ARGBroker 16th Tech Group"
NOMECLATURA: Nombres de Clases: PascalCase
Atributos y Métodos: SnakeCase

**Comment by ValeGuglielmetti** [comment]
El contexto: Esta aplicación, en esta primera etapa, está destinada a usuarios individuales, empresas e instituciones que desean simula la compra y venta de acciones de empresas argentinas.
El objetivo: La aplicación solicitada tiene como objetivo simular las transacciones de compra y venta de acciones entre inversores dentro de MERVAL. La plataforma permitirá a los inversores cosultar cotizaciones en tiempo real y realizar transacciones de manera segura y eficiente.
El alcance: La aplicacion va a estar en español y utilizara pesos argentinos.

**Comment by Fran7890** [comment]
mediante esta primera etapa el contexto que se llevo a cabo simular  se definia especificamente en los usuarios, empresa y la accion de vender y comprar acciones  de empresas argentinas.
El principal objetivo que tiene la aplicacion es que atravez de ella se pueda  comprar y vender aciciones entre inversores dentro de merval , esta plataforma le permitira a los inversores las cotizaciones en tiempo real ofreciendole total seguridad a los clientes y usuarios de la organizacion misma  sobre sus datos personales, ademas de ofrecer seguridad y las cotizaciones obtendras otras funcionalidades que le brindara al clente  mas satisfecho de utilizarla como por ejemplo llevando  un listado de ganacias y perdidas que  puede llevar a cabo de un tiempo , el alcance que a  llevar la aplicacion se maneja en moneda argentina y va a estar disponibles para todos los idomas  para distintos  inversores a futuros.

**Comment by GuillermoGiraudo7** [comment]
Las clases que elegimos para confeccionar el diagrama son:
Inversor: contiene los datos de la persona que se registra en el bróker y luego se crea una billetera para poder operar. También contiene un perfil de inversor, los datos de su domicilio, si es una persona expuesta políticamente, una dirección de correo electrónico y una contraseña para poder ingresar.
Localidad: es el registro de datos de domicilio del inversor. La localidad está asociada a una provincia, ya que cada localidad pertenece solamente a una provincia.
Provincia: son los datos de las provincias del país. Los datos de la misma van a derivar en la localidad que se elija ya que cada provincia posee muchas localidades.
Perfil Inversor: se le asigna un perfil a cada inversor cuando crea la cuenta según el perfil financiero del usuario. Cada tipo de inversor puede tener varios inversores, pero el inversor tiene un solo perfil.
Billetera: contiene la cantidad de dinero en pesos argentinos que el inversor posee, la cantidad y el nombre de las acciones que posee, el total invertido, las ganancias y pérdidas y un número identificador de la misma.
Operacion: es la clase que actúa como intermediaria entre la Acción (que sale de una empresa) y la Billetera que es donde el inversor posee los fondos y la cantidad de acciones que tiene una vez que compra y vende las mismas.
Accion: es la parte de la empresa que el inversor compra/vende. Describe el nombre de la empresa y los valores de compra/venta de la misma. Tiene un precio de compra, otro de venta y las cantidades máximas de cada una para realizar operaciones.

**Comment by Fran7890** [comment]
Al momento que uno o varios accionistas están interesado en querer invertir en la organización ARGBtoker, pasan a ser inversores los cuales al momento de iniciar se tendrán que crear una cuenta en la billetera virtual   que se le recomendara la organización para garantizar la seguridad y confiabilidad al cliente respecto a la información personal de   cada personas las cuales son necesarias para la base de datos de la empresa así puede llevar un control y gestión de los inversionistas que se posee, los datos a pedir pueden ser  dirección, país/ciudad/provincia. La relación entre un inversor y su perfil inversor es fundamental para la toma de decisiones Financieras, El usuario inversor es una evaluación de las características, necesidades y objetivos de un inversor que permite definir el tipo de inversiones más adecuadas para su situación financiera, tolerancia de riesgo, horizonte temporal y objetivos Esto es esencial para lograr una estrategia de inversión exitosa y sostenible.
Al momento de crear un usuario en la plataforma pasaran a ser un perfil inversor donde se relacionarán con la billetera digital esta misma es una herramienta esencial para el usuario ya que es la que proporcionara los medios necesarios para gestionar los fondos  y mantener un control efectivo sobre sus inversiones a su esto permitirá a la persona poder gestionar diferentes tipos de  transacciones que posee la aplicación, las cuales los inversores pueden aprovechar de usarlas: por ejemplo, va a poder ver en tiempo real las acciones de las acciones de la empresa que quiere comprar y vender y vería reflejado el minuto a minuto de cómo cambian los valores monetarios de la organización .
 La relación entre billetera y operaciones es crucial para el inversionista ya que la billetera es por el medio en donde ocurren, pasan y se gestionan todas las acciones económicas llevadas a cabo por el usuario asegurando que se realicen de manera eficiente, segura y transparente, los  movimientos que el inversor haga en la billetera como ver  las ganancias , compras y saldo de la cuenta le facilitara al usuario llevar una mejor gestión de  sus ingresos.
