### ISSUE TITLE
Documentación Diagrama de Relaciones

### ISSUE THREAD

**Issue by CryptoEmpireR4** [16th-Tech-Group/ARGBroker-Demo#20]

**Comment by HeymeCoraspe** [comment]
Para la creación del modelo relacional, partimos del diagrama ER
https://app.diagrams.net/#G1HT6dDCyYrLQaDuDrs8Z47Ysqj9nIWSNZ

Inicialmente se creó la tabla Inversores que contiene los datos de las personas/empresas que se registran, cada inversor tiene una billetera asociada y un perfil de inversor.

El perfil inversor se asigna según perfil crediticio. Cada inversor tendría un perfil y los perfiles pueden tener varios o ningún inversor asignado.

La tabla localidad permite a la persona registrar su domicilio en una provincia y después en una localidad. La localidad está contenida en una provincia y la provincia puede tener muchas localidades.

En la billetera el inversor va a tener los datos de sus operaciones, la cantidad de acciones que posee con su valor promedio. Un saldo en pesos (inicialmente es de $1.000.000, y se irá sumando a este monto, el dinero que obtenga de las acciones vendidas. También podrá ver el balance total que está constituido por el saldo en pesos y el monto que tenga en inversiones. El atributo PNL será las ganancias o pérdidas que tenga. La billetera está asociada a un único inversor y este a su vez puede poseer solo una billetera. También a una o varias operaciones

Las operaciones se registrarán en la tabla con el mismo nombre. Contendrá el tipo de operación (compra/venta), el precio de la operación, la cantidad de acciones (de una misma empresa) que compra/vende, la fecha de realización y el monto de comisión del broker por la operación.  Cada operación estará asociada a 1 billetera.

Cada acción estará asociada a una o ninguna operación (si no ha sido comprada). En el detalle de la tabla acciones tendremos su identificador, el nombre de la empresa a la que pertenece, el volumen y precio de compra/venta diaria, el precio de apertura inicial, el cierre y el mínimo y máximo alcanzados.
