### ISSUE TITLE
Describir quiénes y ante quien deben matricularse a nivel provincial para ejercer la Profesión

### ISSUE THREAD

**Issue by CryptoEmpireR4** [16th-Tech-Group/ARGBroker-Demo#3]
En proceso

**Comment by GuillermoGiraudo7** [comment]
Dentro de nuestro equipo de trabajo, todos debemos estar matriculados ante el Consejo Profesional de Ciencias Informáticas de la Provincia de Córdoba, según las disposiciones de la Ley N° 7642/87 para poder realizar nuestro trabajo dentro del marco de la ley.
