### ISSUE TITLE
Requerimientos del código programado y las bases de datos según la legislación vigente 

### ISSUE THREAD

**Issue by CryptoEmpireR4** [16th-Tech-Group/ARGBroker-Demo#4]
Describir qué requerimientos deben cumplir el código programado y las bases de datos según la legislación vigente · Enumerar los pasos para que ARGBroker sea parte del Registro Nacional de software.

En proceso: GUIRAUDO, GUILLERMO

**Comment by GuillermoGiraudo7** [comment]
Teniendo en cuenta la Ley N° 11.723 de Propiedad Intelectual, los requerimientos que debe cumplir el código programado y las bases de datos: que las mismas sean originales, es decir, una creación nueva de nuestra organización y no una copia. Se debe ir documentando el proceso de trabajo e ir regularizando las bases de datos y el código para una mejor organización. Para mayor protección se recomienda la inscripción en la Dirección Nacional del Derecho de Autor para facilitar la defensa en un hipotético juicio.
Dentro del contrato de trabajo se puede especificar que los derechos de autor son del empleador, como también poner una cláusula de licencia para que los autores conserven este derecho.
Para ser parte del Registro Nacional de Software hay que inscribirse en el mismo. Los requisitos son: completar el formulario de inscripción, presentar copia del DNI y constancia de inscripción de Afip de los autores, constancia de CUIT y completar una declaración jurada. Los pasos a seguir para dicha inscripción son: registrarse en la plataforma de Trámites a Distancia del Gobierno, cargar la documentación que se requiera para el caso y esperar la revisión por parte del organismo para obtener la licencia.
