### ISSUE TITLE
Si un integrante del grupo divulga los datos de la base de datos interna, describir como legalmente deberían actuar los demás

### ISSUE THREAD

**Issue by CryptoEmpireR4** [16th-Tech-Group/ARGBroker-Demo#7]
En proceso.

**Comment by ValeGuglielmetti** [comment]
Suponiendo que Luciano Cañas divulgue los datos de la base de datos interna, los demás integrantes del grupo deberían actuar rápidamente apartándolo del cargo y bloqueando todos los accesos internos y externos para asegurar la base de datos y de esta manera detener la divulgación. Estas acciones estarían amparadas por la Ley 25326 que señala que los responsables deben garantizar la seguridad y confidencialidad de los datos, evitando la pérdida o tratamiento no autorizado de los mismos.
