### ISSUE TITLE
Si otro integrante del grupo reutiliza el código para fines personales a nivel internacional, describir qué instrumento legal respalda a ARGBroker.

### ISSUE THREAD

**Issue by CryptoEmpireR4** [16th-Tech-Group/ARGBroker-Demo#9]
En proceso.

**Comment by dorgnachj** [comment]
Si un compañero utiliza el codigo para bienes personales a nivel internacional,el instumrnto que nos respalda son:
Derechos de autor internacionales: La Convención de Berna para la Protección de las Obras Literarias y Artísticas es un tratado internacional que protege los derechos de autor.
Tratados de Propiedad Intelectual Bilaterales o Multilaterales: Además de la Convención de Berna, existen tratados internacionales más específicos que pueden respaldar los derechos de propiedad intelectual de ARGBroker.
Jurisdicción extraterritorial: Dependiendo de la jurisdicción en la que se haya replicado el código, ARGBroker puede considerar emprender acciones legales en los tribunales internacionales o en los tribunales de los países donde se ha producido la infracción.

**Comment by dorgnachj** [comment]
Los miembros del grupo tienen derecho a proteger su propiedad intelectual y pueden tomar acciones legales tanto a nivel provincial como nacional para detener el uso no autorizado del código y buscar una compensación por los daños ocasionados. La clave es actuar de manera organizada, recolectar evidencias y buscar asesoramiento legal adecuado para garantizar que sus derechos sean defendidos adecuadamente.
